
CREATE TABLE DIM_AFFILIE (
    NUM_AFF NUMBER PRIMARY KEY,
    DATE_AFF DATE,
    SECTEUR_ID NUMBER,
    REGION_ID NUMBER,
    VILLE_ID NUMBER
);


CREATE TABLE DIM_REGION (
    REGION_ID NUMBER PRIMARY KEY,
    LIBELLE_REGION VARCHAR2(100)
);

CREATE TABLE DIM_VILLE (
    VILLE_ID NUMBER PRIMARY KEY,
    LIBELLE_VILLE VARCHAR2(100),
    REGION_ID NUMBER,
    CONSTRAINT FK_VILLE_REGION_1 FOREIGN KEY (REGION_ID)
        REFERENCES DIM_REGION(REGION_ID)
);

CREATE TABLE DIM_SECTEUR (
    SECTEUR_ID NUMBER PRIMARY KEY,
    LIBELLE_SECTEUR VARCHAR2(100)
);
CREATE TABLE DIM_IMMATRICULE (
    NUM_IMMA    NUMBER PRIMARY KEY,
    NUM_AFF     NUMBER,
    DATE_ENTREE DATE,
    CONSTRAINT FK_DIM_IMMA_AFF FOREIGN KEY (NUM_AFF)
        REFERENCES DIM_AFFILIE(NUM_AFF)
);

-- Création de la table FAIT_PAYEMENT 
CREATE TABLE FAIT_PAYEMENT (
    NUM_AFF       NUMBER NOT NULL,
    NUM_IMMA      NUMBER NOT NULL,
    PERIODE       NUMBER,
    DEBIT_CNSS    NUMBER,
    DEBIT_AMO     NUMBER,
    DEBIT_TPF     NUMBER,
    CREDIT_CNSS   NUMBER,
    CREDIT_TPF    NUMBER,
    PN_CNSS       NUMBER,
    PN_TPF        NUMBER,

    -- Colonnes calculées 
    TOTAL_DEBIT NUMBER GENERATED ALWAYS AS (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) VIRTUAL,
    TOTAL_CREDIT NUMBER GENERATED ALWAYS AS (CREDIT_CNSS + CREDIT_TPF) VIRTUAL,
    TAUX_RECOUVREMENT NUMBER(6,4) GENERATED ALWAYS AS
        (CASE WHEN (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) = 0 
              THEN 0 
              ELSE (CREDIT_CNSS + CREDIT_TPF)/(DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) END) VIRTUAL,
    FLAG_IMPAYE NUMBER GENERATED ALWAYS AS
        (CASE WHEN (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF - (CREDIT_CNSS + CREDIT_TPF)) > 0 
              THEN 1 ELSE 0 END) VIRTUAL,
    MONTANT_NET NUMBER GENERATED ALWAYS AS
        ((DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) - (CREDIT_CNSS + CREDIT_TPF)) VIRTUAL,
    TOTAL_PENALITE NUMBER GENERATED ALWAYS AS (PN_CNSS + PN_TPF) VIRTUAL,
    RATIO_PENALITE NUMBER(6,4) GENERATED ALWAYS AS
        (CASE WHEN (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) = 0 
              THEN 0 
              ELSE (PN_CNSS + PN_TPF)/(DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) END) VIRTUAL,
    MONTANT_RISQUE NUMBER GENERATED ALWAYS AS (DEBIT_CNSS - CREDIT_CNSS) VIRTUAL,

    -- Clés étrangères
    CONSTRAINT FK_PAYEMENT_AFF FOREIGN KEY (NUM_AFF)
        REFERENCES DIM_AFFILIE(NUM_AFFILIE),
    CONSTRAINT FK_PAYEMENT_IMMA FOREIGN KEY (NUM_IMMA)
        REFERENCES DIM_IMMATRICULE(NUM_IMMA)
);


CREATE TABLE FAIT_SALAIRE (
    NUM_AFF       NUMBER,
    NUM_IMMA      NUMBER,
    PERIODE       DATE,
    SALAIRE_BRUTE NUMBER(15,2),
    FLAG_SALAIRE VARCHAR2(20) GENERATED ALWAYS AS (
        CASE 
            WHEN SALAIRE_BRUTE < 3000 THEN 'BAS'
            WHEN SALAIRE_BRUTE BETWEEN 3000 AND 6000 THEN 'MOYEN'
            WHEN SALAIRE_BRUTE > 6000 THEN 'ELEVÉ'
            ELSE 'NON DEFINI'
        END
    ) VIRTUAL,

    CONSTRAINT FK_FS_AFF FOREIGN KEY (NUM_AFF)
        REFERENCES DIM_AFFILIE(NUM_AFF),

    CONSTRAINT FK_FS_IMMA FOREIGN KEY (NUM_IMMA)
        REFERENCES DIM_IMMATRICULE(NUM_IMMA)
);




-- DIM_REGION
INSERT INTO DIM_REGION (REGION_ID, LIBELLE_REGION)
SELECT DISTINCT REGION_ID, LIBELLE_REGION
FROM REGION;

-- DIM_VILLE
INSERT INTO DIM_VILLE (VILLE_ID, LIBELLE_VILLE, REGION_ID)
SELECT DISTINCT VILLE_ID, LIBELLE_VILLE, REGION_ID
FROM VILLE;

-- DIM_SECTEUR
INSERT INTO DIM_SECTEUR (SECTEUR_ID, LIBELLE_SECTEUR)
SELECT DISTINCT SECTEUR_ID, LIBELLE_SECTEUR
FROM SECTEUR;

-- DIM_AFFILIE
INSERT INTO DIM_AFF (NUM_AFFILIE, DATE_AFF, SECTEUR_ID, REGION_ID, VILLE_ID)
SELECT DISTINCT NUM_AFF, DATE_AFF, SECTEUR_ID, REGION_ID, VILLE_ID
FROM AFF;

-- DIM_IMMATRICULE
INSERT INTO DIM_IMMATRICULE (NUM_IMMA, NUM_AFF, DATE_ENTREE)
SELECT DISTINCT NUM_IMMA, NUM_AFF, DATE_ENTREE
FROM IMMA;
-- FAIT_PAYEMENT
INSERT INTO FAIT_PAYEMENT (
    NUM_AFF, PERIODE, DEBIT_CNSS, DEBIT_AMO, DEBIT_TPF,
    CREDIT_CNSS, CREDIT_TPF, PN_CNSS, PN_TPF
)
SELECT 
    NUM_AFF,   
    PERIODE,
    DEBIT_CNSS,
    DEBIT_AMO,
    DEBIT_TPF,
    CREDIT_CNSS,
    CREDIT_TPF,
    PN_CNSS,
    PN_TPF
FROM PAYEMENT;


INSERT INTO FAIT_SALAIRE (NUM_AFF, NUM_IMMA, PERIODE, SALAIRE_BRUTE)
SELECT NUM_AFF, NUM_IMMA, PERIODE, SALAIRE_BRUTE
FROM SAL;
DROP TABLE FAIT_PAYEMENT CASCADE CONSTRAINTS;
CREATE TABLE FAIT_PAYEMENT (
    NUM_AFF       NUMBER NOT NULL,
    PERIODE       NUMBER,
    DEBIT_CNSS    NUMBER,
    DEBIT_AMO     NUMBER,
    DEBIT_TPF     NUMBER,
    CREDIT_CNSS   NUMBER,
    CREDIT_TPF    NUMBER,
    PN_CNSS       NUMBER,
    PN_TPF        NUMBER,


    TOTAL_DEBIT NUMBER GENERATED ALWAYS AS (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) VIRTUAL,
    TOTAL_CREDIT NUMBER GENERATED ALWAYS AS (CREDIT_CNSS + CREDIT_TPF) VIRTUAL,

    TAUX_RECOUVREMENT_CNSS_AMO NUMBER(6,4) GENERATED ALWAYS AS
        (CASE WHEN (DEBIT_CNSS + DEBIT_AMO) = 0 
              THEN 0 
              ELSE (CREDIT_CNSS )/(DEBIT_CNSS + DEBIT_AMO) END) VIRTUAL,

    TAUX_RECOUVREMENT_TPF NUMBER(6,4) GENERATED ALWAYS AS
        (CASE WHEN DEBIT_TPF = 0 THEN 0 ELSE CREDIT_TPF / DEBIT_TPF END) VIRTUAL,

    MONTANT_RISQUE_CNSS_AMO NUMBER GENERATED ALWAYS AS
        (GREATEST((DEBIT_CNSS + DEBIT_AMO) - (CREDIT_CNSS ),0)) VIRTUAL,

    MONTANT_RISQUE_TPF NUMBER GENERATED ALWAYS AS
        (GREATEST(DEBIT_TPF - CREDIT_TPF,0)) VIRTUAL,


    FLAG_PENALITE NUMBER GENERATED ALWAYS AS
        (CASE WHEN (PN_CNSS + PN_TPF) > 0 THEN 1 ELSE 0 END) VIRTUAL,

    FLAG_CLEAN NUMBER GENERATED ALWAYS AS
        (CASE WHEN (CREDIT_CNSS + CREDIT_TPF) >= (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF)
              THEN 1 ELSE 0 END) VIRTUAL,

    CONSTRAINT FK_PAYEMENT_AFF FOREIGN KEY (NUM_AFF)
        REFERENCES DIM_AFFILIE(NUM_AFF)
);

INSERT INTO FAIT_PAYEMENT (
    NUM_AFF,
    PERIODE,
    DEBIT_CNSS,
    DEBIT_AMO,
    DEBIT_TPF,
    CREDIT_CNSS,
    CREDIT_TPF,
    PN_CNSS,
    PN_TPF
)
SELECT
    NUM_AFF,
    PERIODE,
    DEBIT_CNSS,
    DEBIT_AMO,
    DEBIT_TPF,
    CREDIT_CNSS,
    CREDIT_TPF,
    PN_CNSS,
    PN_TPF
FROM PAYEMENT;

ALTER TABLE FAIT_PAYEMENT DROP COLUMN FLAG_IMPAYE;
ALTER TABLE FAIT_PAYEMENT
ADD FLAG_CLEAN NUMBER GENERATED ALWAYS AS
(
    CASE 
        WHEN (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF) = 0 THEN 0
        WHEN ((CREDIT_CNSS + CREDIT_TPF) / (DEBIT_CNSS + DEBIT_AMO + DEBIT_TPF)) >= 0.98
        THEN 1 
        ELSE 0 
    END
) VIRTUAL;

select count(*) from aff;--152834
select count(*) from imma;--2092899
select count(*) from sal;--75344364
select count(*) from payement;--5502024
select count(*) from secteur;--19
select count(*) from ville;--45
select count(*) from region;--11
SELECT COUNT(*) 
FROM FAIT_PAYEMENT
WHERE FLAG_CLEAN = 1;--23,8% bon payeur















--features engineering
CREATE TABLE FEATURES_PAYEMENT AS

WITH base AS (
    SELECT 
        NUM_AFF,
        PERIODE,
        SUBSTR(PERIODE,1,4) AS ANNEE,
        TO_DATE(PERIODE || '01','YYYYMMDD') AS PER_DATE,

        DEBIT_CNSS,
        DEBIT_AMO,
        DEBIT_TPF,
        CREDIT_CNSS,
        CREDIT_TPF,

        PN_CNSS,
        PN_TPF

    FROM FAIT_PAYEMENT
),

/* max date par affilié + année */
year_max AS (
    SELECT 
        NUM_AFF,
        SUBSTR(PERIODE,1,4) AS ANNEE,
        MAX(TO_DATE(PERIODE || '01','YYYYMMDD')) AS MAX_DATE_YEAR
    FROM FAIT_PAYEMENT
    GROUP BY NUM_AFF, SUBSTR(PERIODE,1,4)
)

SELECT 
    b.NUM_AFF,
    b.ANNEE,

    SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0)) AS TOTAL_DEBIT,

    SUM(NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0)) AS TOTAL_CREDIT,

    GREATEST(
        SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0))
        -
        SUM(NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0))
    ,0) AS MONTANT_IMPAYE,

    SUM(NVL(b.PN_CNSS,0) + NVL(b.PN_TPF,0)) AS TOTAL_PENALITE,

    CASE 
        WHEN SUM(NVL(b.PN_CNSS,0) + NVL(b.PN_TPF,0)) > 0 THEN 1
        ELSE 0
    END AS FLAG_PENALITE,

    ROUND(
        CASE 
            WHEN SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0)) = 0 
            THEN 0
            ELSE 
                SUM(NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0)) /
                SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0))
        END
    ,4) AS TAUX_RECOUVREMENT,

    ROUND(
        CASE 
            WHEN SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0)) = 0 
            THEN 0
            ELSE 
                1 -
                (
                    SUM(NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0)) /
                    SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0))
                )
        END
    ,4) AS TAUX_IMPAYE,

    CASE 
        WHEN SUM(NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0)) /
             NULLIF(SUM(NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0)),0) >= 0.98
        THEN 1 ELSE 0
    END AS FLAG_CLEAN,

    SUM(
        CASE 
            WHEN (NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0))
               > (NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0))
            THEN 1 ELSE 0
        END
    ) AS NB_IMPAYE_12M,

    SUM(
        CASE 
            WHEN b.PER_DATE >= ADD_MONTHS(y.MAX_DATE_YEAR, -3)
             AND (NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0))
               > (NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0))
            THEN 1 ELSE 0
        END
    ) AS NB_IMPAYE_3M,

    SUM(
        CASE 
            WHEN b.PER_DATE >= ADD_MONTHS(y.MAX_DATE_YEAR, -6)
             AND (NVL(b.DEBIT_CNSS,0) + NVL(b.DEBIT_AMO,0) + NVL(b.DEBIT_TPF,0))
               > (NVL(b.CREDIT_CNSS,0) + NVL(b.CREDIT_TPF,0))
            THEN 1 ELSE 0
        END
    ) AS NB_IMPAYE_6M

FROM base b

JOIN year_max y
  ON b.NUM_AFF = y.NUM_AFF
 AND b.ANNEE = y.ANNEE

GROUP BY 
    b.NUM_AFF,
    b.ANNEE;

CREATE TABLE FEATURES_DIM_AFFILIE AS
SELECT 

    a.NUM_AFF,
    a.DATE_AFF,
    ROUND((SYSDATE - a.DATE_AFF)/365, 2) AS AGE_ENTREPRISE,
    a.SECTEUR_ID,
    s.LIBELLE_SECTEUR,
    a.REGION_ID,
    r.LIBELLE_REGION,
    a.VILLE_ID,
    v.LIBELLE_VILLE
    
FROM DIM_AFFILIE a
LEFT JOIN DIM_SECTEUR s ON a.SECTEUR_ID = s.SECTEUR_ID
LEFT JOIN DIM_REGION r ON a.REGION_ID = r.REGION_ID
LEFT JOIN DIM_VILLE v ON a.VILLE_ID = v.VILLE_ID;






CREATE TABLE SAL_STAT AS
SELECT 
    NUM_AFF,
    EXTRACT(YEAR FROM PERIODE) AS ANNEE,
    AVG(SALAIRE_BRUTE) AS SALAIRE_BRUTE_AVG,
    MAX(SALAIRE_BRUTE) AS SALAIRE_BRUTE_MAX,
    MIN(SALAIRE_BRUTE) AS SALAIRE_BRUTE_MIN
FROM FAIT_SALAIRE
WHERE EXTRACT(YEAR FROM PERIODE) BETWEEN 2022 AND 2024
GROUP BY NUM_AFF, EXTRACT(YEAR FROM PERIODE);

UPDATE SAL_STAT
SET SALAIRE_BRUTE_AVG = ROUND(SALAIRE_BRUTE_AVG, 4);


CREATE TABLE NB_IMMA AS
SELECT 
    NUM_AFF,
    EXTRACT(YEAR FROM PERIODE) AS ANNEE,
    COUNT(DISTINCT NUM_IMMA) AS NB_IMMA
FROM FAIT_SALAIRE
WHERE EXTRACT(YEAR FROM PERIODE) BETWEEN 2022 AND 2024
GROUP BY NUM_AFF, EXTRACT(YEAR FROM PERIODE);

-- Creation table finale

CREATE TABLE FEATURES_IMMATRICULE AS
SELECT 
    f.NUM_AFF,
    f.ANNEE,
    s.SALAIRE_BRUTE_AVG,
    s.SALAIRE_BRUTE_MAX,
    s.SALAIRE_BRUTE_MIN,
    NVL(n.NB_IMMA, 0) AS NB_IMMA, 
    t.TARGET_CLASS
FROM FEATURES_PAYEMENT f
LEFT JOIN SAL_STAT s ON f.NUM_AFF = s.NUM_AFF AND f.ANNEE = s.ANNEE
LEFT JOIN NB_IMMA n ON f.NUM_AFF = n.NUM_AFF AND f.ANNEE = n.ANNEE
LEFT JOIN TARGET_AFF t ON f.NUM_AFF = t.NUM_AFF AND f.ANNEE = t.ANNEE;



    


    




