--------------------------------------------------------
--  File created - Tuesday-April-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "PFE"."REGION" 
   (	"REGION_ID" NUMBER, 
	"LIBELLE_REGION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VILLE
--------------------------------------------------------

  CREATE TABLE "PFE"."VILLE" 
   (	"VILLE_ID" NUMBER, 
	"LIBELLE_VILLE" VARCHAR2(100 BYTE), 
	"REGION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAL
--------------------------------------------------------

  CREATE TABLE "PFE"."SAL" 
   (	"NUM_AFF" NUMBER, 
	"SALAIRE_BRUTE" NUMBER(15,2), 
	"NUM_IMMA" NUMBER, 
	"PERIODE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYEMENT
--------------------------------------------------------

  CREATE TABLE "PFE"."PAYEMENT" 
   (	"NUM_AFF" NUMBER, 
	"NUM_IMMA" NUMBER, 
	"PERIODE" NUMBER, 
	"DEBIT_CNSS" NUMBER, 
	"DEBIT_AMO" NUMBER, 
	"DEBIT_TPF" NUMBER, 
	"CREDIT_CNSS" NUMBER, 
	"CREDIT_TPF" NUMBER, 
	"PN_CNSS" NUMBER, 
	"PN_TPF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMMA
--------------------------------------------------------

  CREATE TABLE "PFE"."IMMA" 
   (	"NUM_IMMA" NUMBER, 
	"NUM_AFF" NUMBER, 
	"DATE_ENTREE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTEUR
--------------------------------------------------------

  CREATE TABLE "PFE"."SECTEUR" 
   (	"SECTEUR_ID" NUMBER, 
	"LIBELLE_SECTEUR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AFF
--------------------------------------------------------

  CREATE TABLE "PFE"."AFF" 
   (	"NUM_AFF" NUMBER, 
	"DATE_AFF" DATE, 
	"SECTEUR_ID" NUMBER, 
	"REGION_ID" NUMBER, 
	"VILLE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007346
--------------------------------------------------------

  CREATE UNIQUE INDEX "PFE"."SYS_C007346" ON "PFE"."REGION" ("REGION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007348
--------------------------------------------------------

  CREATE UNIQUE INDEX "PFE"."SYS_C007348" ON "PFE"."VILLE" ("VILLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PAYEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PFE"."PK_PAYEMENT" ON "PFE"."PAYEMENT" ("NUM_AFF", "PERIODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007354
--------------------------------------------------------

  CREATE UNIQUE INDEX "PFE"."SYS_C007354" ON "PFE"."IMMA" ("NUM_IMMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007347
--------------------------------------------------------

  CREATE UNIQUE INDEX "PFE"."SYS_C007347" ON "PFE"."SECTEUR" ("SECTEUR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007350
--------------------------------------------------------

  CREATE UNIQUE INDEX "PFE"."SYS_C007350" ON "PFE"."AFF" ("NUM_AFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "PFE"."REGION" ADD PRIMARY KEY ("REGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VILLE
--------------------------------------------------------

  ALTER TABLE "PFE"."VILLE" ADD PRIMARY KEY ("VILLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SAL
--------------------------------------------------------

  ALTER TABLE "PFE"."SAL" MODIFY ("NUM_AFF" NOT NULL ENABLE);
  ALTER TABLE "PFE"."SAL" MODIFY ("NUM_IMMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYEMENT
--------------------------------------------------------

  ALTER TABLE "PFE"."PAYEMENT" MODIFY ("NUM_AFF" NOT NULL ENABLE);
  ALTER TABLE "PFE"."PAYEMENT" ADD CONSTRAINT "PK_PAYEMENT" PRIMARY KEY ("NUM_AFF", "PERIODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMMA
--------------------------------------------------------

  ALTER TABLE "PFE"."IMMA" ADD PRIMARY KEY ("NUM_IMMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECTEUR
--------------------------------------------------------

  ALTER TABLE "PFE"."SECTEUR" ADD PRIMARY KEY ("SECTEUR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AFF
--------------------------------------------------------

  ALTER TABLE "PFE"."AFF" ADD PRIMARY KEY ("NUM_AFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VILLE
--------------------------------------------------------

  ALTER TABLE "PFE"."VILLE" ADD CONSTRAINT "FK_VILLE_REGION" FOREIGN KEY ("REGION_ID")
	  REFERENCES "PFE"."REGION" ("REGION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMMA
--------------------------------------------------------

  ALTER TABLE "PFE"."IMMA" ADD CONSTRAINT "FK_IMMA_AFF" FOREIGN KEY ("NUM_AFF")
	  REFERENCES "PFE"."AFF" ("NUM_AFF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFF
--------------------------------------------------------

  ALTER TABLE "PFE"."AFF" ADD CONSTRAINT "FK_AFF_SECTEUR" FOREIGN KEY ("SECTEUR_ID")
	  REFERENCES "PFE"."SECTEUR" ("SECTEUR_ID") ENABLE;
  ALTER TABLE "PFE"."AFF" ADD CONSTRAINT "FK_AFF_REGION" FOREIGN KEY ("REGION_ID")
	  REFERENCES "PFE"."REGION" ("REGION_ID") ENABLE;
  ALTER TABLE "PFE"."AFF" ADD CONSTRAINT "FK_AFF_VILLE" FOREIGN KEY ("VILLE_ID")
	  REFERENCES "PFE"."VILLE" ("VILLE_ID") ENABLE;
